name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'artworkia-capstone-public/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: artlink-backend
  AZURE_WEBAPP_PACKAGE_PATH: './artworkia-capstone-public/src/WebApi'
  DOTNET_VERSION: '7.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build with dotnet
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet build --configuration Release
      
      - name: Publish with dotnet
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet publish -c Release -o ./publish
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish
